name: ci

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - '[0-9]+.x'
    paths-ignore:
      - 'docs/**'
      - '*.md'
  pull_request:

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: set up Go 1.x
        uses: actions/setup-go@v3
        with:
          go-version: ^1.18

      - name: checkout
        uses: actions/checkout@v3

      - name: deps
        run: make deps

      - name: staticcheck
        uses: dominikh/staticcheck-action@v1.2.0
        with:
          version: "2022.1.1"
          install-go: false

      - name: vet
        run: make vet

      - name: test
        run: make cov

      - name: upload coverage
        uses: codecov/codecov-action@v3

  release:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')
    needs:
      - build
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body_path: CHANGELOG.md
          draft: false
          prerelease: contains(github.ref, '-')

  automerge:
    needs:
      - build
    runs-on: ubuntu-latest
    if: >
      github.event_name == 'pull_request' &&
      github.event.pull_request.user.login == 'dependabot[bot]'
    permissions:
      pull-requests: write
      contents: write
    steps:
      - uses: fastify/github-action-merge-dependabot@v3.2.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
